// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ehdykquraokasocxcicb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVoZHlrcXVyYW9rYXNvY3hjaWNiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc4ODMwMDUsImV4cCI6MjA3MzQ1OTAwNX0.LDxSHnNgb5_geyCqfpV_mQsdjPIi5MTLQF_jWufFcTk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});